.pragma library

var PACK = {
    "alias": { "file": "alias.png", "hotX": 3, "hotY": 3, "frames": 1, "delay": 0 },
    "all-scroll": { "file": "all-scroll.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 },
    "bottom_left_corner": { "file": "bottom_left_corner.png", "hotX": 3, "hotY": 20, "frames": 1, "delay": 0 },
    "bottom_right_corner": { "file": "bottom_right_corner.png", "hotX": 20, "hotY": 20, "frames": 1, "delay": 0 },
    "bottom_side": { "file": "bottom_side.png", "hotX": 12, "hotY": 20, "frames": 1, "delay": 0 },
    "cell": { "file": "cell.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 },
    "center_ptr": { "file": "center_ptr.png", "hotX": 12, "hotY": 3, "frames": 1, "delay": 0 },
    "col-resize": { "file": "col-resize.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "color-picker": { "file": "color-picker.png", "hotX": 2, "hotY": 21, "frames": 1, "delay": 0 },
    "context-menu": { "file": "context-menu.png", "hotX": 3, "hotY": 3, "frames": 1, "delay": 0 },
    "copy": { "file": "copy.png", "hotX": 3, "hotY": 3, "frames": 1, "delay": 0 },
    "crosshair": { "file": "crosshair.png", "hotX": 13, "hotY": 13, "frames": 1, "delay": 0 },
    "default": { "file": "default.png", "hotX": 3, "hotY": 3, "frames": 1, "delay": 0 },
    "dnd-move": { "file": "dnd-move.png", "hotX": 12, "hotY": 12, "frames": 1, "delay": 0 },
    "dnd-no-drop": { "file": "dnd-no-drop.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 },
    "down-arrow": { "file": "down-arrow.png", "hotX": 12, "hotY": 20, "frames": 1, "delay": 0 },
    "draft": { "file": "draft.png", "hotX": 2, "hotY": 21, "frames": 1, "delay": 0 },
    "fleur": { "file": "fleur.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 },
    "help": { "file": "help.png", "hotX": 3, "hotY": 3, "frames": 1, "delay": 0 },
    "left-arrow": { "file": "left-arrow.png", "hotX": 3, "hotY": 11, "frames": 1, "delay": 0 },
    "left_side": { "file": "left_side.png", "hotX": 3, "hotY": 11, "frames": 1, "delay": 0 },
    "no-drop": { "file": "no-drop.png", "hotX": 3, "hotY": 3, "frames": 1, "delay": 0 },
    "not-allowed": { "file": "not-allowed.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "openhand": { "file": "openhand.png", "hotX": 12, "hotY": 12, "frames": 1, "delay": 0 },
    "pencil": { "file": "pencil.png", "hotX": 2, "hotY": 21, "frames": 1, "delay": 0 },
    "pirate": { "file": "pirate.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 },
    "pointer": { "file": "pointer.png", "hotX": 12, "hotY": 3, "frames": 1, "delay": 0 },
    "progress": { "file": "progress.png", "hotX": 3, "hotY": 3, "frames": 23, "delay": 30 },
    "right-arrow": { "file": "right-arrow.png", "hotX": 20, "hotY": 11, "frames": 1, "delay": 0 },
    "right_ptr": { "file": "right_ptr.png", "hotX": 21, "hotY": 3, "frames": 1, "delay": 0 },
    "right_side": { "file": "right_side.png", "hotX": 20, "hotY": 11, "frames": 1, "delay": 0 },
    "row-resize": { "file": "row-resize.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "size_bdiag": { "file": "size_bdiag.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "size_fdiag": { "file": "size_fdiag.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "size_hor": { "file": "size_hor.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "size_ver": { "file": "size_ver.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "text": { "file": "text.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "top_left_corner": { "file": "top_left_corner.png", "hotX": 4, "hotY": 3, "frames": 1, "delay": 0 },
    "top_right_corner": { "file": "top_right_corner.png", "hotX": 19, "hotY": 3, "frames": 1, "delay": 0 },
    "top_side": { "file": "top_side.png", "hotX": 12, "hotY": 3, "frames": 1, "delay": 0 },
    "up-arrow": { "file": "up-arrow.png", "hotX": 11, "hotY": 3, "frames": 1, "delay": 0 },
    "vertical-text": { "file": "vertical-text.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "wait": { "file": "wait.png", "hotX": 12, "hotY": 11, "frames": 23, "delay": 30 },
    "wayland-cursor": { "file": "wayland-cursor.png", "hotX": 12, "hotY": 12, "frames": 1, "delay": 0 },
    "x-cursor": { "file": "x-cursor.png", "hotX": 12, "hotY": 11, "frames": 1, "delay": 0 },
    "zoom-in": { "file": "zoom-in.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 },
    "zoom-out": { "file": "zoom-out.png", "hotX": 11, "hotY": 11, "frames": 1, "delay": 0 }
};

var ALIASES = {
    "00000000000000020006000e7e9ffc3f": "progress",
    "00008160000006810000408080010102": "size_ver",
    "03b6e0fcb3499374a867c041f52298f0": "not-allowed",
    "08e8e1c95fe2fc01f976f1e063a24ccd": "progress",
    "1081e37283d90000800003c07f3ef6bf": "copy",
    "3085a0e285430894940527032f8b26df": "alias",
    "3ecb610c1bf2410f44200f48c40d3599": "progress",
    "4498f0e0c1937ffe01fd06f973665830": "dnd-move",
    "5c6cd98b3f3ebcb1f9c7f1c204630408": "help",
    "6407b0e94181790501fd1e167b474872": "copy",
    "640fb0e74195791501fd1ed57b41487f": "alias",
    "9081237383d90e509aa00f00170e968f": "dnd-move",
    "9d800788f1b08800ae810202380a0822": "pointer",
    "a2a266d0498c3104214a47bd64ab0fc8": "alias",
    "alias": "alias",
    "all-scroll": "all-scroll",
    "arrow": "default",
    "b66166c04f8c3109214a4fbd64a50fc8": "copy",
    "bottom_left_corner": "bottom_left_corner",
    "bottom_right_corner": "bottom_right_corner",
    "bottom_side": "bottom_side",
    "cell": "cell",
    "center_ptr": "center_ptr",
    "circle": "not-allowed",
    "closedhand": "dnd-move",
    "col-resize": "col-resize",
    "color-picker": "color-picker",
    "context-menu": "context-menu",
    "copy": "copy",
    "cross": "crosshair",
    "crossed_circle": "not-allowed",
    "crosshair": "crosshair",
    "d9ce0ab605698f320427677b458ad60b": "help",
    "default": "default",
    "dnd-copy": "copy",
    "dnd-move": "dnd-move",
    "dnd-no-drop": "dnd-no-drop",
    "dnd-none": "dnd-move",
    "down-arrow": "down-arrow",
    "draft": "draft",
    "e-resize": "size_hor",
    "e29285e634086352946a0e7090d73106": "pointer",
    "ew-resize": "size_hor",
    "fcf21c00b30f7e3f83fe0dfd12e71cff": "dnd-move",
    "fleur": "fleur",
    "forbidden": "no-drop",
    "grab": "openhand",
    "grabbing": "dnd-move",
    "h_double_arrow": "size_hor",
    "half-busy": "progress",
    "hand1": "pointer",
    "hand2": "pointer",
    "help": "help",
    "ibeam": "text",
    "left-arrow": "left-arrow",
    "left_ptr": "default",
    "left_ptr_help": "help",
    "left_ptr_watch": "progress",
    "left_side": "left_side",
    "link": "alias",
    "move": "dnd-move",
    "n-resize": "size_ver",
    "ne-resize": "size_bdiag",
    "nesw-resize": "size_bdiag",
    "no-drop": "no-drop",
    "not-allowed": "not-allowed",
    "ns-resize": "size_ver",
    "nw-resize": "size_fdiag",
    "nwse-resize": "size_fdiag",
    "openhand": "openhand",
    "pencil": "pencil",
    "pirate": "pirate",
    "plus": "cell",
    "pointer": "pointer",
    "pointing_hand": "pointer",
    "progress": "progress",
    "question_arrow": "help",
    "right-arrow": "right-arrow",
    "right_ptr": "right_ptr",
    "right_side": "right_side",
    "row-resize": "row-resize",
    "s-resize": "size_ver",
    "sb_h_double_arrow": "size_hor",
    "sb_v_double_arrow": "size_ver",
    "se-resize": "size_fdiag",
    "size-bdiag": "default",
    "size-fdiag": "default",
    "size-hor": "default",
    "size-ver": "default",
    "size_all": "fleur",
    "size_bdiag": "size_bdiag",
    "size_fdiag": "size_fdiag",
    "size_hor": "size_hor",
    "size_ver": "size_ver",
    "split_h": "col-resize",
    "split_v": "row-resize",
    "sw-resize": "size_bdiag",
    "tcross": "crosshair",
    "text": "text",
    "top_left_arrow": "default",
    "top_left_corner": "top_left_corner",
    "top_right_corner": "top_right_corner",
    "top_side": "top_side",
    "up-arrow": "up-arrow",
    "v_double_arrow": "size_ver",
    "vertical-text": "vertical-text",
    "w-resize": "size_hor",
    "wait": "wait",
    "watch": "wait",
    "wayland-cursor": "wayland-cursor",
    "whats_this": "help",
    "x-cursor": "x-cursor",
    "xterm": "text",
    "zoom-in": "zoom-in",
    "zoom-out": "zoom-out"
};

function canon(name) {
    var key = String(name || "default")
    if (ALIASES[key])
        key = ALIASES[key]
    if (PACK[key])
        return key
    return "default"
}

function spec(name) {
    return PACK[canon(name)]
}

function fromCss(raw) {
    var name = String(raw || "default").split(",")[0].trim().toLowerCase()
    if (name === "auto" || name === "none" || name === "")
        name = "default"
    return canon(name)
}

